complete -f -c peco -l help -s h        -d "show help message and exit"
complete -f -c peco -l tty              -d "path to the TTY (usually, the value of \$TTY)"
complete -f -c peco -l query            -d "initial value for query"
complete -f -c peco -l rcfile           -d "path to the settings file"
complete -f -c peco -l version          -d "print the version and exit"
complete -f -c peco -l buffer-size -s b -d "number of lines to keep in search buffer"
complete -f -c peco -l null             -d "expect NUL (\0) as separator for target/output"
complete -f -c peco -l initial-index    -d "position of the initial index of the selection (0 base)"
complete -f -c peco -l initial-matcher  -d "specify the default matcher (deprecated)"
complete -f -c peco -l initial-filter   -d "specify the default filter"
complete -f -c peco -l prompt           -d "specify the prompt string"
complete -f -c peco -l layout           -d "layout to be used 'top-down' (default) or 'bottom-up'" -a "top-down bottom-up"
